services:
#    matuck_menu.example:
#        class: matuck\MenuBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
     matuckMenu.twig.menu_extension:
         class: matuck\MenuBundle\Twig\MenuExtension
         arguments: ["@doctrine.orm.entity_manager", "@security.access_map", "@security.authorization_checker"]
         tags:
            - { name: twig.extension }